### ISSUE TITLE
Ported from Classic-GATK: ClipReads functionality for quality-based clipping

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/hellbender#263] opened 2015-03-07 04:55 UTC
Found this improvement request in the Classic GATK Pivotal. Would be good to check whether this is satisfied by the ported version.

----

Quality-based clipping should be more straightforward than it is. As explained by Mauricio in relation to this forum question:

http://gatk.vanillaforums.com/discussion/comment/13108#Comment_13108

"As implemented it doesn't really clip all bases below a certain threshold. It does something gnarly. It keeps a running sum and sets the clipping point to where the running sum exceeds the threshold after subtracting the qual for each base. It only traverses from the end of the read (depending on read orientation). 

Essentially , this is a tool to hard clip bad read ends from the sequencer (meaning, the last few cycles) in case the sum of their qualities is not large enough. Not at all what our user wanted. Instead, he was looking for a very simple if statement here. Which I also think would be much more useful."

Here are Mark's comments:

     * Clip bases from the read in clipper from
     * <p/>
     * argmax_x{ \sum{i = x + 1}^l (qTrimmingThreshold - qual)
     * <p/>
     * to the end of the read.  This is blatantly stolen from BWA.
     * <p/>
     * Walk through the read from the end (in machine cycle order) to the beginning, calculating the
     * running sum of qTrimmingThreshold - qual.  While we do this, we track the maximum value of this
     * sum where the delta > 0.  After the loop, clipPoint is either -1 (don't do anything) or the
     * clipping index in the read (from the end).

**Comment by akiezun** [comment] 2015-04-15 16:37
@vdauwera can you clarify? is this a bug or an enhancement?

**Comment by vdauwera** [comment] 2015-04-20 02:38
It depends if the current implemented functionality is useful or not. If yes, then this is an enhancement (to ultimately have both functionalities). If not, then this is a bug (to replace the current functionality by the desired one).  

Maybe Yossi could weigh in on use cases?

**Comment by yfarjoun** [comment] 2015-04-20 11:56
This sounds like the EAMS filter that is implemented in Picard picard/illumina/parser/BclParser.java 

The purpose of this filter is to convert the ends of reads for which the quality has deteriorated and convert them to 2. This used to be a filter that illumina ran on their data as they converted to fasta but since we wanted to convert BCL directly to bam we implemented this in our code-base. I'm not sure why it is in GATK (perhaps one could look in the commit message) as it doesn't seem to be needed given the current pipeline.

**Comment by vdauwera** [comment] 2015-04-22 09:43
Initial commit by Mark DP in 2009: 

> simpleComplement function() in BaseUtils. Generic framework for clipp…
>…ing reads along with tests. Support for Q score based clipping, sequence-specific clipping (not1), and clipping of ranges of bases (cycles 1-5, 10-15 for example). Can write out clipped bases as Ns, quality scores as 0s, or in the future will support softclipping the bases themselves.

https://github.com/broadinstitute/gsa-unstable/commit/d6385e0d884cbd80c34e16e848297c3694f85a5a

**Comment by akiezun** [comment] 2015-05-06 03:12
I'm still unclear if this is a bug or enhancement. Does the current ClipReads do what it promises to do? If yes, then it's not a bug. If not, what is the test case that shows the bug?

**Comment by yfarjoun** [comment] 2015-08-11 00:57
I think we can close this issue.

**Closed** 2015-08-11 01:07 UTC
Labels: PRIORITY_LOW

**Comment by vdauwera** [comment] 2015-08-11 04:20
For the record I don't think we should be enabling users to do quality based trimming anyway. It's just awkward to have a tool that's not doing what it promises to do (purportedly). @akiezun Can I assume that this tool will never be ported to GATK4?

**Comment by eitanbanks** [comment] 2015-08-11 11:21
Why not?  I found it very useful recently...

**Comment by eitanbanks** [comment] 2015-08-11 21:10
Just wanted to clarify:
The basic functionality of the ClipReads tool is very useful.  I used it for the bam reduction project and now I'm about to use it again for the rapid QC project.  This definitely should get ported to GATK4.
However, it's only the basic stuff (clipping by cycle, writing out as N's, etc.) that we need to keep.  The "gnarly" running sum thing is something we can trash.

**Comment by vdauwera** [comment] 2015-08-11 21:13
Sounds like the kind of functionality you'd want in read transformers, rather than as a dedicated walker, no?

**Comment by eitanbanks** [comment] 2015-08-11 21:16
Depends on how it works in GATK4.  Removing bases didn't work for LocusWalkers in GATK3 (it broke LIBS).

**Comment by vdauwera** [comment] 2015-08-11 21:19
@akiezun @lbergelson @droazen How does one find out more about read transformer functionality in Hellbender (ie the general design + what specific functionalities are already implemented)?

**Comment by akiezun** [comment] 2015-08-12 02:09
ClipReads is already ported. Can we resolve whether this ticket is a bug report or an enhancement request or neither?

@vdauwera nope, but there's the code!

**Comment by eitanbanks** [comment] 2015-08-12 02:13
@akiezun if the code is truly doing a running sum and setting the clipping point to where the running sum exceeds the threshold, then we should change it.  Just clip the tails that are below the Q threshold.

**Comment by akiezun** [comment] 2015-08-12 02:59
i cannot reopen without a test case.
