### ISSUE TITLE
Run "cloud" and "bucket" test groups on travis

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#552] opened 2015-06-09 15:20 UTC
These should be run in parallel to our existing tests since they're very slow at the moment.  We need to provide a private key for these, so they will not succeed on external pull requests.  On external pull requests someone will have to manually sign off on these.

**Comment by droazen** [comment] 2015-07-22 16:17
Closing as dupe of https://github.com/broadinstitute/hellbender/issues/656

**Closed by droazen** 2015-07-22 16:17 UTC
Labels: tests
